# Generated by Django 3.0.3 on 2020-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200317_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_category',
            new_name='Event_Category',
        ),
        migrations.AddField(
            model_name='event',
            name='event_slug_two',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
