# Generated by Django 3.0.3 on 2020-03-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200317_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Event_Category',
            new_name='event_category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_slug',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_slug_two',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='category_slug',
        ),
    ]
