# Generated by Django 3.0.3 on 2020-03-17 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200317_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date_of_event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
