# Generated by Django 3.0.3 on 2020-03-22 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200317_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organizer_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='category_summary',
        ),
        migrations.AddField(
            model_name='event',
            name='max_Team_size',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.EventCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='event_category',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Organizer', verbose_name='Organizer'),
        ),
    ]
