# Generated by Django 3.0.3 on 2020-05-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
