# Generated by Django 3.0.3 on 2020-05-28 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category_search',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
