# Generated by Django 3.0.3 on 2020-05-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_event_category_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category_search',
        ),
    ]
