# Generated by Django 3.0.3 on 2020-05-29 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_event_category_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_content',
            new_name='event_brief',
        ),
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
