# Generated by Django 3.0.3 on 2020-05-29 19:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200529_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('registration_time', models.DateTimeField(verbose_name='Time Registered')),
                ('team_members_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), null=True, size=None)),
                ('team_members_age', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), null=True, size=None)),
                ('max_Team_size', models.PositiveIntegerField(default=1)),
                ('User_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.EventCategory', verbose_name='Category')),
                ('organizer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Organizer', verbose_name='Organizer')),
            ],
        ),
    ]
