# Generated by Django 3.0.3 on 2020-05-29 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='User_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.User', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='organizer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Organizer', verbose_name='Organizer'),
        ),
    ]
