# Generated by Django 3.0.3 on 2020-05-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200530_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='max_Team_size',
            new_name='team_size',
        ),
    ]
