# Generated by Django 3.0.3 on 2020-05-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200530_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='User_Id',
        ),
        migrations.AddField(
            model_name='registration',
            name='event_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Event', verbose_name='Event Id'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.User', verbose_name='UserID'),
        ),
    ]
