# Generated by Django 3.0.3 on 2020-05-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200530_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='organizer_id',
        ),
    ]
