# Generated by Django 3.0.3 on 2020-05-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_registration_organizer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time Registered'),
        ),
    ]
