# Generated by Django 3.0.3 on 2020-05-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200530_0354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
