# Generated by Django 3.0.3 on 2020-05-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='team_members_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team_members_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
