# Generated by Django 3.0.3 on 2020-05-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200530_1256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='EventRegistration',
        ),
    ]
