# Generated by Django 3.0.3 on 2020-05-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200530_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='event_category',
            field=models.CharField(default='Unknown', max_length=200, unique=True),
        ),
    ]
