# Generated by Django 3.0.3 on 2020-05-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200530_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='Organizer_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
